package com.gbcomp.proyjavaybdd.view;

import com.gbcomp.proyjavaybdd.contoller.DBController;
import com.gbcomp.proyjavaybdd.model.dto.DTOcategorias;
import java.time.LocalDate;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author cuent
 */
public class AgregarTransaccion extends javax.swing.JDialog {
    
    private DBController controlador;
    private LocalDate Fecha = LocalDate.now();

    /**
     * Creates new form agregarTransaccion
     */
    public AgregarTransaccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
    }
    
    public void setControlador(DBController controlador) {
        this.controlador = controlador;
        this.iniciarCategorias();
        
    }
    
    public void iniciarCategorias() {
        
        for (DTOcategorias categoria : this.controlador.seleccionarCategorias()) {
            
            ((DefaultComboBoxModel) this.cbCategoria.getModel())
                    .addElement(categoria);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoGasto = new javax.swing.ButtonGroup();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        timePicker2 = new com.github.lgooddatepicker.components.TimePicker();
        pPrincipal = new javax.swing.JPanel();
        pTitulo = new javax.swing.JPanel();
        lbNueva = new javax.swing.JLabel();
        lbTransaccion = new javax.swing.JLabel();
        pMonto = new javax.swing.JPanel();
        tfMonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pCategoria = new javax.swing.JPanel();
        lbCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        pTipoGasto = new javax.swing.JPanel();
        lbTipoGasto = new javax.swing.JLabel();
        pRbGastos = new javax.swing.JPanel();
        rbGasto = new javax.swing.JRadioButton();
        rbIngreso = new javax.swing.JRadioButton();
        pDescripcion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        pFecha = new javax.swing.JPanel();
        lbFecha = new javax.swing.JLabel();
        btnSeleccionarFecha = new javax.swing.JButton();
        pBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pPrincipal.setLayout(new java.awt.GridLayout(7, 0, 0, 10));

        pTitulo.setLayout(new java.awt.GridLayout(2, 0));

        lbNueva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNueva.setText("NUEVA");
        lbNueva.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pTitulo.add(lbNueva);

        lbTransaccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTransaccion.setText("TRANSACCION");
        lbTransaccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pTitulo.add(lbTransaccion);

        pPrincipal.add(pTitulo);

        tfMonto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tfMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMonto.setText("0");
        tfMonto.setBackground(new java.awt.Color(246, 246, 246));
        tfMonto.setBorder(null);
        tfMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMontoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("$");

        javax.swing.GroupLayout pMontoLayout = new javax.swing.GroupLayout(pMonto);
        pMonto.setLayout(pMontoLayout);
        pMontoLayout.setHorizontalGroup(
            pMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMontoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pMontoLayout.setVerticalGroup(
            pMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMontoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pPrincipal.add(pMonto);

        pCategoria.setLayout(new java.awt.GridLayout(2, 0));

        lbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCategoria.setText("Categoria");
        pCategoria.add(lbCategoria);

        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });
        pCategoria.add(cbCategoria);

        pPrincipal.add(pCategoria);

        pTipoGasto.setLayout(new java.awt.GridLayout(2, 0));

        lbTipoGasto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTipoGasto.setText("Tipo de gasto");
        lbTipoGasto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pTipoGasto.add(lbTipoGasto);

        pRbGastos.setLayout(new java.awt.GridLayout(1, 5));

        btgTipoGasto.add(rbGasto);
        rbGasto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbGasto.setText("Gasto");
        rbGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGastoActionPerformed(evt);
            }
        });
        pRbGastos.add(rbGasto);

        btgTipoGasto.add(rbIngreso);
        rbIngreso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbIngreso.setText("Ingreso");
        rbIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIngresoActionPerformed(evt);
            }
        });
        pRbGastos.add(rbIngreso);

        pTipoGasto.add(pRbGastos);

        pPrincipal.add(pTipoGasto);

        pDescripcion.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descripcion");
        pDescripcion.add(jLabel1);

        tfDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pDescripcion.add(tfDescripcion);

        pPrincipal.add(pDescripcion);

        pFecha.setLayout(new java.awt.GridLayout(2, 0));

        lbFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFecha.setText("Fecha");
        pFecha.add(lbFecha);

        btnSeleccionarFecha.setText("Seleccionar fecha");
        btnSeleccionarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarFechaActionPerformed(evt);
            }
        });
        pFecha.add(btnSeleccionarFecha);

        pPrincipal.add(pFecha);

        pBotones.setLayout(new java.awt.GridLayout(1, 3));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pBotones.add(btnAgregar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pBotones.add(btnCancelar);

        pPrincipal.add(pBotones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMontoActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void rbGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbGastoActionPerformed

    private void rbIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIngresoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        if (this.tfMonto.getText().isBlank()
                || this.btgTipoGasto.getSelection() == null
                || this.tfDescripcion.getText().isBlank()) {
            
            JOptionPane.showMessageDialog(this, "ERROR", "Campos invalidos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.controlador.agregar(
                this.tfDescripcion.getText(),
                this.tfMonto.getText(),
                this.cbCategoria
                        .getSelectedItem().toString(),
                this.Fecha,
                this.getSelectedRadioBTN());
        
        this.setVisible(false);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSeleccionarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFechaActionPerformed
       
        SeleccionarFecha fecha = new SeleccionarFecha(null, true);
        fecha.setVisible(true);
               
        this.Fecha = fecha.getFecha();
        
    }//GEN-LAST:event_btnSeleccionarFechaActionPerformed
    
    private String getSelectedRadioBTN() {
        
        Enumeration<AbstractButton> btns = btgTipoGasto.getElements();
        
        AbstractButton btn = btns.nextElement();
        
        if (btn.isSelected()) {
            return btn.getText();
        } else {
            return btns.nextElement().getText();
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarTransaccion dialog = new AgregarTransaccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipoGasto;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionarFecha;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNueva;
    private javax.swing.JLabel lbTipoGasto;
    private javax.swing.JLabel lbTransaccion;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pCategoria;
    private javax.swing.JPanel pDescripcion;
    private javax.swing.JPanel pFecha;
    private javax.swing.JPanel pMonto;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pRbGastos;
    private javax.swing.JPanel pTipoGasto;
    private javax.swing.JPanel pTitulo;
    private javax.swing.JRadioButton rbGasto;
    private javax.swing.JRadioButton rbIngreso;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfMonto;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    private com.github.lgooddatepicker.components.TimePicker timePicker2;
    // End of variables declaration//GEN-END:variables

}
